### ISSUE TITLE
Fast way to add jira link

### ISSUE THREAD

**Issue by srudakov** [VadimBalabin/jirainfo#1]
It would be easier for user to have special button on edit page menu that would add jira link template on page(<ji key="JRA-000">JRA-000</ji>). And user will have to write correct id only. For now user has to waste time on copy past such template or write whole link manually.

**Comment by srudakov** [comment]
Instead of just "JRA-000" it supposed to be `<ji key="JRA-000">JRA-000</ji>`, sorry.

**Comment by dehahost** [comment]
More than a button for adding a JIRA ticket link, it would be useful to have some kind of autodetection of the JIRA ticket - like [this DokuWiki plugin](https://www.dokuwiki.org/plugin:jiralinks) had.

**Comment by eugenyk** [comment]
@VadimBalabin , are you going to make a release in order to update your plugin in a standard way?
